import { Deck, Card } from './types/firebase';

export const DEMO_DECKS: Deck[] = [
  { 
    id: 'initial-deck', 
    title: 'World Capitals', 
    icon: '🌍', 
    color: '#1cb0f6', 
    category: 'Geography', 
    description: 'Master countries and their capitals.', 
    difficulty: 1, 
    minLevel: 1 
  },
  { 
    id: 'math-bases', 
    title: 'Math Basics', 
    icon: '🔢', 
    color: '#58cc02', 
    category: 'STEM', 
    description: 'Essential arithmetic and concepts.', 
    difficulty: 1, 
    minLevel: 1 
  },
  { 
    id: 'general-knowledge', 
    title: 'General Knowledge', 
    icon: '🧠', 
    color: '#ff4b4b', 
    category: 'Trivia', 
    description: 'A mix of facts from history, science, and pop culture.', 
    difficulty: 1, 
    minLevel: 1 
  },
  { 
    id: 'guess-the-flag', 
    title: 'Guess the Flag', 
    icon: '🚩', 
    color: '#1cb0f6', 
    category: 'Geography', 
    description: 'Learn to recognize world flags at a glance!', 
    difficulty: 1, 
    minLevel: 1 
  },
  { 
    id: 'space-facts', 
    title: 'Cosmic Journey', 
    icon: '🚀', 
    color: '#ce82ff', 
    category: 'Science', 
    description: 'Fascinating facts about our Universe.', 
    difficulty: 3, 
    minLevel: 3 
  },
  { 
    id: 'nature-guess', 
    title: 'Nature Guess', 
    icon: '🌿', 
    color: '#ffa500', 
    category: 'Nature', 
    description: 'Guess the animals and plants from images!', 
    difficulty: 1, 
    minLevel: 1 
  },
  { 
    id: 'english-mastery', 
    title: 'English Mastery', 
    icon: '📚', 
    color: '#ce82ff', 
    category: 'Languages', 
    description: 'Master grammar, tenses, and common proverbs.', 
    difficulty: 1, 
    minLevel: 1 
  },
  { 
    id: 'advanced-science', 
    title: 'Advanced Science', 
    icon: '🧪', 
    color: '#1cb0f6', 
    category: 'STEM', 
    description: 'Deeper dive into biology and chemistry.', 
    difficulty: 2, 
    minLevel: 2 
  },
  { 
    id: 'history-legends', 
    title: 'History Legends', 
    icon: '🏰', 
    color: '#ffc800', 
    category: 'History', 
    description: 'Ancient civilizations and heroic tales.', 
    difficulty: 3, 
    minLevel: 3 
  },
  { 
    id: 'famous-monuments', 
    title: 'Famous Monuments', 
    icon: '🏛️', 
    color: '#1cb0f6', 
    category: 'Geography', 
    description: 'Identify iconic landmarks from around the globe.', 
    difficulty: 4, 
    minLevel: 4 
  },
  { 
    id: 'medical-diagnostic', 
    title: 'Medical Diagnostic', 
    icon: '🩺', 
    color: '#ff4b4b', 
    category: 'Science', 
    description: 'Can you name the disease based on these symptoms?', 
    difficulty: 4, 
    minLevel: 4 
  },
];

export const DEMO_CARDS: Record<string, Omit<Card, 'id' | 'deckId'>[]> = {
  'initial-deck': [
    { front: 'What is the capital of France?', back: 'Paris' },
    { front: 'What is the capital of Japan?', back: 'Tokyo' },
    { front: 'What is the capital of Brazil?', back: 'Brasília' },
    { front: 'What is the capital of Canada?', back: 'Ottawa' },
    { front: 'What is the capital of Australia?', back: 'Canberra' },
    { front: 'What is the capital of United Kingdom?', back: 'London' },
    { front: 'What is the capital of Germany?', back: 'Berlin' },
    { front: 'What is the capital of Italy?', back: 'Rome' },
    { front: 'What is the capital of Spain?', back: 'Madrid' },
    { front: 'What is the capital of China?', back: 'Beijing' },
  ],
  'advanced-science': [
    { front: 'What is the powerhouse of the cell?', back: 'Mitochondria' },
    { front: 'What is the atomic number of Carbon?', back: '6' },
    { front: 'What is the first element in the periodic table?', back: 'Hydrogen' },
    { front: 'What gas do humans breathe out?', back: 'Carbon dioxide' },
    { front: 'What is the average human body temperature in Celsius?', back: '37°C' },
    { front: 'What is known as the "universal solvent"?', back: 'Water' },
    { front: 'What is the pH level of pure water?', back: '7' },
    { front: 'What is the strongest bone in the human body?', back: 'Femur' },
    { front: 'Which organ is responsible for filtering blood?', back: 'Kidneys' },
    { front: 'What is the speed of light approx?', back: '300,000 km/s' },
  ],
  'history-legends': [
    { front: 'Who was the first emperor of Rome?', back: 'Augustus' },
    { front: 'In what year was the Magna Carta signed?', back: '1215' },
    { front: 'In what year did World War II end?', back: '1945' },
    { front: 'Who is officially credited with discovering America in 1492?', back: 'Christopher Columbus' },
    { front: 'Who was the first President of the United States?', back: 'George Washington' },
    { front: 'Which ancient civilization built the pyramids?', back: 'Egyptians' },
    { front: 'Who invented the lightbulb?', back: 'Thomas Edison' },
    { front: 'Which French Queen is famously (but falsely) associated with the phrase "Let them eat cake"?', back: 'Marie Antoinette' },
    { front: 'In what year did the Berlin Wall fall?', back: '1989' },
    { front: 'Who was the founder of the Mongol Empire?', back: 'Genghis Khan' },
  ],
  'math-bases': [
    { front: 'What is 12 x 12?', back: '144' },
    { front: 'What is the square root of 81?', back: '9' },
    { front: 'What is 15% of 200?', back: '30' },
    { front: 'What is 7 + 8 x 2?', back: '23', hint: 'Remember BODMAS/PEMDAS: multiply before adding.' },
    { front: 'How many degrees are in a triangle?', back: '180°' },
    { front: 'What is 9 x 7?', back: '63' },
    { front: 'What is the square root of 144?', back: '12' },
    { front: 'What is 20% of 500?', back: '100' },
    { front: 'What is (10 + 5) / 3?', back: '5' },
    { front: 'How many degrees are in a circle?', back: '360°' },
  ],
  'general-knowledge': [
    { front: 'Which is the largest ocean on Earth?', back: 'Pacific' },
    { front: 'Who painted the Mona Lisa?', back: 'Leonardo da Vinci' },
    { front: 'What is the chemical symbol for Gold?', back: 'Au' },
    { front: 'In which year did the Titanic sink?', back: '1912' },
    { front: 'Which planet is closest to the Sun?', back: 'Mercury' },
    { front: 'Which is the largest continent by area?', back: 'Asia' },
    { front: 'Who is the author of the Harry Potter series?', back: 'J.K. Rowling' },
    { front: 'What is the largest mammal in the world?', back: 'Blue Whale' },
    { front: 'How many elements are in the periodic table?', back: '118' },
    { front: 'In what year did humans first land on the Moon?', back: '1969' },
  ],
  'guess-the-flag': [
    { front: 'Identify this country flag.', back: 'Brazil', imageUrl: 'https://flagcdn.com/w640/br.png' },
    { front: 'Which country does this flag belong to?', back: 'Japan', imageUrl: 'https://flagcdn.com/w640/jp.png' },
    { front: 'Identify this European country flag.', back: 'Germany', imageUrl: 'https://flagcdn.com/w640/de.png' },
    { front: 'Guess the country!', back: 'Canada', imageUrl: 'https://flagcdn.com/w640/ca.png' },
    { front: 'Identify this African country flag.', back: 'South Africa', imageUrl: 'https://flagcdn.com/w640/za.png' },
    { front: 'Which country has this tricolor flag?', back: 'France', imageUrl: 'https://flagcdn.com/w640/fr.png' },
    { front: 'Identify the flag of this island nation.', back: 'United Kingdom', imageUrl: 'https://flagcdn.com/w640/gb.png' },
    { front: 'Stars and Stripes represents which country?', back: 'United States', imageUrl: 'https://flagcdn.com/w640/us.png' },
    { front: 'Green, White, and Red vertical stripes belong to?', back: 'Italy', imageUrl: 'https://flagcdn.com/w640/it.png' },
    { front: 'Which country flag is this?', back: 'Spain', imageUrl: 'https://flagcdn.com/w640/es.png' },
  ],
  'space-facts': [
    { front: 'Which planet is known as the Red Planet?', back: 'Mars' },
    { front: 'What is the largest planet in our solar system?', back: 'Jupiter' },
    { front: 'What galaxy do we live in?', back: 'The Milky Way' },
    { front: 'How many moons does Earth have?', back: 'One' },
    { front: 'What is the closest star to Earth?', back: 'The Sun' },
    { front: 'What is the hottest planet in our solar system?', back: 'Venus' },
    { front: 'Which is the smallest planet in our solar system?', back: 'Mercury' },
    { front: 'Which planet is famous for its prominent ring system?', back: 'Saturn' },
    { front: 'Who was the first human to travel into space?', back: 'Yuri Gagarin' },
    { front: 'How long does it take for light from the Sun to reach Earth approx?', back: '8 minutes' },
  ],
  'nature-guess': [
    { front: 'What is this animal?', back: 'Lion', imageUrl: 'https://images.pexels.com/photos/247502/pexels-photo-247502.jpeg?auto=compress&cs=tinysrgb&h=400' },
    { front: 'Identify this tree species.', back: 'Oak', imageUrl: 'https://images.pexels.com/photos/1632790/pexels-photo-1632790.jpeg?auto=compress&cs=tinysrgb&h=400', hint: 'Known for producing acorns.' },
    { front: 'What is this beautiful flower?', back: 'Rose', imageUrl: 'https://images.pexels.com/photos/6617180/pexels-photo-6617180.jpeg?auto=compress&cs=tinysrgb&h=400' },
    { front: 'Guess this insect.', back: 'Butterfly', imageUrl: 'https://images.pexels.com/photos/672142/pexels-photo-672142.jpeg?auto=compress&cs=tinysrgb&h=400' },
    { front: 'What large mammal is this?', back: 'Elephant', imageUrl: 'https://images.pexels.com/photos/1054655/pexels-photo-1054655.jpeg?auto=compress&cs=tinysrgb&h=400' },
    { front: 'Identify this bright yellow flower.', back: 'Sunflower', imageUrl: 'https://images.pexels.com/photos/1390433/pexels-photo-1390433.jpeg?auto=compress&cs=tinysrgb&h=400' },
    { front: 'What animal is this relative of the dog?', back: 'Wolf', imageUrl: 'https://images.pexels.com/photos/34474941/pexels-photo-34474941.jpeg?auto=compress&cs=tinysrgb&h=400' },
    { front: 'Identify this exotic flower.', back: 'Orchid', imageUrl: 'https://images.pexels.com/photos/15413508/pexels-photo-15413508.jpeg?auto=compress&cs=tinysrgb&h=400' },
    { front: 'What intelligent marine mammal is this?', back: 'Dolphin', imageUrl: 'https://images.pexels.com/photos/27768664/pexels-photo-27768664.jpeg?auto=compress&cs=tinysrgb&h=400' },
  ],
  'english-mastery': [
    { front: 'The sun ___ in the east.', back: 'Rises', hint: 'Present simple tense for universal truths.' },
    { front: 'Better late than ___.', back: 'Never', hint: 'Complete the proverb.' },
    { front: 'What is the past tense of "Go"?', back: 'Went' },
    { front: 'A ___ in need is a ___ indeed.', back: 'Friend', hint: 'The missing word is the same for both blanks.' },
    { front: 'Which is correct: "They is" or "They are"?', back: 'They are' },
    { front: 'What is the plural of "Mouse"?', back: 'Mice' },
    { front: 'What is the antonym of "Ancient"?', back: 'Modern' },
    { front: 'What does the idiom "A piece of cake" mean?', back: 'Very easy' },
    { front: 'Complete the idiom: "The ___ is on the other foot."', back: 'Shoe' },
    { front: 'Which is the correct spelling: "Receive" or "Recieve"?', back: 'Receive' },
  ],
  'famous-monuments': [
    { front: 'Which city is home to the Eiffel Tower?', back: 'Paris', imageUrl: 'https://images.pexels.com/photos/32494860/pexels-photo-32494860.jpeg?auto=compress&cs=tinysrgb&h=400' },
    { front: 'In which city is the Faisal Mosque located?', back: 'Islamabad', imageUrl: 'https://images.pexels.com/photos/15817294/pexels-photo-15817294.jpeg?auto=compress&cs=tinysrgb&h=400' },
    { front: 'Where would you find the Statue of Liberty?', back: 'New York', imageUrl: 'https://images.pexels.com/photos/356844/pexels-photo-356844.jpeg?auto=compress&cs=tinysrgb&h=400' },
    { front: 'Which country hosts the Taj Mahal?', back: 'India', imageUrl: 'https://images.pexels.com/photos/1603650/pexels-photo-1603650.jpeg?auto=compress&cs=tinysrgb&h=400' },
    { front: 'Name the city containing the Colosseum.', back: 'Rome', imageUrl: 'https://images.pexels.com/photos/532263/pexels-photo-532263.jpeg?auto=compress&cs=tinysrgb&h=400' },
    { front: 'Which structure is visible from space and located in China?', back: 'Great Wall of China', imageUrl: 'https://images.pexels.com/photos/31639350/pexels-photo-31639350.jpeg?auto=compress&cs=tinysrgb&h=400' },
    { front: 'In which country is Machu Picchu located?', back: 'Peru', imageUrl: 'https://images.pexels.com/photos/2929906/pexels-photo-2929906.jpeg?auto=compress&cs=tinysrgb&h=400' },
    { front: 'Where is the "Christ the Redeemer" statue located?', back: 'Rio de Janeiro, Brazil', imageUrl: 'https://images.pexels.com/photos/11051182/pexels-photo-11051182.jpeg?auto=compress&cs=tinysrgb&h=400' },
    { front: 'In which city can you find the Pyramids of Giza?', back: 'Giza, Egypt', imageUrl: 'https://images.pexels.com/photos/28013729/pexels-photo-28013729.jpeg?auto=compress&cs=tinysrgb&h=400' },
    { front: 'Which ancient city in Jordan is carved into rock?', back: 'Petra', imageUrl: 'https://images.pexels.com/photos/36283919/pexels-photo-36283919.jpeg?auto=compress&cs=tinysrgb&h=400' },
  ],
  'medical-diagnostic': [
    { front: 'Symptoms: High fever, stiff neck, and headache.', back: 'Meningitis' },
    { front: 'Symptoms: Polydipsia (thirst), polyuria, and high blood sugar.', back: 'Diabetes' },
    { front: 'Symptoms: Sudden chest pain, shortness of breath, radiating to left arm.', back: 'Heart Attack' },
    { front: 'Symptoms: wheezing, coughing, and chest tightness.', back: 'Asthma' },
    { front: 'Condition characterized by low red blood cell count.', back: 'Anemia' },
    { front: 'Common viral infection often called the "flu".', back: 'Influenza' },
    { front: 'Medical term for high blood pressure.', back: 'Hypertension' },
    { front: 'Inflammation of one or more joints.', back: 'Arthritis' },
    { front: 'Inflammation of the appendix.', back: 'Appendicitis' },
    { front: 'Condition caused by interruption of blood flow to the brain.', back: 'Stroke' },
  ]
};